description: >
  LibVMI is a C library with Python bindings that makes it easy to
  monitor the low-level details of a running virtual machine by
  viewing its memory, trapping on hardware events, and accessing
  the vCPU registers. This is called virtual machine introspection.
baseurl: ""
url: "http://www.libvmi.com"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude: ["publish.sh", "parse-doxygen-xml.py", "image_sources", "py_apiparse"]
